// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB493egFQ5DZ7YuNDMPSgnP1h1dCDLNBIo',
    appId: '1:410983509658:web:62089bbb4ec48268963923',
    messagingSenderId: '410983509658',
    projectId: 'coursez-50fb3',
    authDomain: 'coursez-50fb3.firebaseapp.com',
    storageBucket: 'coursez-50fb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4s2KF9ZBz6JDA0id3JgkRc36o2Mgy8c',
    appId: '1:410983509658:android:4d655c821d63fb46963923',
    messagingSenderId: '410983509658',
    projectId: 'coursez-50fb3',
    storageBucket: 'coursez-50fb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaTcQpFFPqjXDgt7ulF3MwnUn2eab_fjM',
    appId: '1:410983509658:ios:b918f5a6491d8fde963923',
    messagingSenderId: '410983509658',
    projectId: 'coursez-50fb3',
    storageBucket: 'coursez-50fb3.appspot.com',
    iosClientId: '410983509658-tihj55dns7er9ki91su5b8j1e9ifjoe5.apps.googleusercontent.com',
    iosBundleId: 'com.coursez.coursez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaTcQpFFPqjXDgt7ulF3MwnUn2eab_fjM',
    appId: '1:410983509658:ios:b918f5a6491d8fde963923',
    messagingSenderId: '410983509658',
    projectId: 'coursez-50fb3',
    storageBucket: 'coursez-50fb3.appspot.com',
    iosClientId: '410983509658-tihj55dns7er9ki91su5b8j1e9ifjoe5.apps.googleusercontent.com',
    iosBundleId: 'com.coursez.coursez',
  );
}
